categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'new computation'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
      - 'bugfix'
  - title: 'Updates'
    labels:
      - 'refactor'
      - 'documentation'
  - title: 'Breaking Changes'
    labels:
      - 'breaking'
template: |
  ## What's Changed

  $CHANGES