blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/pydata/xarray/discussions
    about: |
      Ask questions about the reV suite (including GAPs) and discuss with
      the developers and other users here. If you have a question like "How
      do convert my function to a CLI using GAPs?" then please include a
      self-contained reproducible example if possible.
