name: Release Documentation

permissions: write-all

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Pull Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: prefix-dev/setup-pixi@v0.8.4
        with:
          pixi-version: v0.44.0
          locked: true
          cache: true

      - name: Build Docs
        run: pixi run -e doc make-html

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
