name: Lint Code Base

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request: null

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    permissions:
        contents: read
        packages: read
        # To report GitHub Actions status checks
        statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
            # super-linter needs the full git history to get the
            # list of files that changed across commits
            fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v6.2.0
        env:
        #   VALIDATE_ALL_CODEBASE: false
          VALIDATE_CHECKOV: false
          VALIDATE_CSS: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON: false
          VALIDATE_MARKDOWN: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_YAML: false
          DEFAULT_BRANCH: origin/main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          PYTHON_PYLINT_CONFIG_FILE: .pylintrc
