name: Python tests (Pixi)

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: prefix-dev/setup-pixi@v0.8.8
      with:
        pixi-version: v0.47.0
        locked: true
        cache: true

    - run: pixi run tests
