name: reV CLI Tests

on: pull_request

jobs:
  rev_cli_tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout gaps
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1
        path: gaps
    - name: checkout reV
      uses: actions/checkout@v2
      with:
        repository: nrel/reV
        fetch-depth: 1
        path: reV
    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.9
    - name: Install reV
      working-directory: ./reV
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: Install gaps
      working-directory: ./gaps
      shell: bash -l {0}
      run: |
        pip install -e .[dev,test]
    - name: Run reV CLI tests
      working-directory: ./reV
      shell: bash -l {0}
      run: |
        pytest -k cli -v --disable-warnings
