name: Upload to PyPi

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Build and upload wheels
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: prefix-dev/setup-pixi@v0.8.8
      with:
        pixi-version: v0.48.0
        locked: true
        cache: true
        cache-write: ${{ github.ref == 'refs/heads/main' }}
        environments: dev

    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: pixi run -e dev upload-wheels
