name: Pytests with specific package versions

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.22.0
        pip install pandas==2.0.0
        python -m pip install .[test]
    - name: Run Pytest
      run: |
        python -m pytest -v --disable-warnings
