name: Python tests with tox

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: "10 13 5,20 * *"
  workflow_dispatch:

jobs:
  test-latest-deps:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.13', '3.12', '3.11', '3.10', '3.9']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Cache pip dependencies (only on main)
      if: github.ref == 'refs/heads/main'
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions>=2.0

    - name: tox cache
      uses: actions/cache@v4
      with:
        path: .tox/
        key: ${{ runner.os }}-${{ matrix.python-version }}-tox-v1-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-tox-v1-

    - name: Save tox cache only on main
      if: github.ref == 'refs/heads/main'
      uses: actions/cache/save@v4
      with:
        path: .tox/
        key: ${{ runner.os }}-${{ matrix.python-version }}-tox-v1-${{ hashFiles('**/pyproject.toml') }}

    - name: Test with tox (pull request)
      run: tox -e latest
      env:
        PYTHONDEVMODE: 1

  test-msv:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions>=2.0

    - name: tox cache
      uses: actions/cache@v4
      with:
        path: .tox/
        key: ${{ runner.os }}-3.9-msv-tox-v1-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-3.9-msv-tox-v1-

    - name: Save tox cache (msv) only on main
      if: github.ref == 'refs/heads/main'
      uses: actions/cache/save@v4
      with:
        path: .tox/
        key: ${{ runner.os }}-3.9-msv-tox-v1-${{ hashFiles('**/pyproject.toml') }}

    - name: Test with tox (pull request)
      if: github.event_name == 'pull_request'
      run: tox -e msv
      env:
        PYTHONDEVMODE: 1

